stages:
  - build
  - test
  - deploy

image: python:3.7-stretch

test job:
  stage: test
  before_script:
    - pip install -r ./requirements.txt -U
  only:
    changes:
      - pysomq/*
      - tests/*
    refs:
      - pushes
      - triggers
      - schedules
      - merge_requests
      - web
  except:
    refs:
      - master
  script:
    - mypy --ignore-missing-imports .
    - UNITTEST=1 pytest --junitxml=results.xml tests/
  artifacts:
    paths:
    reports:
      junit:
        - results.xml

build job:
  stage: build
  before_script:
    - pip install -r ./requirements.txt -U
  only:
    refs:
      - tags
      - master
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/