unit_test:
  stage: test
  image: python:3.7-stretch
  before_script:
    - pip install -r ./requirements.txt -U
  only:
    changes:
      - pysomq/*
      - tests/*
    refs:
      - pushes
      - triggers
      - schedules
      - merge_requests
      - web
  except:
    refs:
      - master
  script:
    - mypy --ignore-missing-imports .
    - UNITTEST=1 pytest --junitxml=results.xml tests/
  artifacts:
    paths:
    reports:
      junit: 
        - results.xml
